keyword: '{botname_lowercase}' # single word only. EX: tag, battlestars, manager, dua, notes
app:
  defaultLanguage: 'en'
  developerId: '{your_user_id}'
  commandSettings:
    ignoreOfficialBots: true
    ignoreUnofficialBots: false

redis:
  host: localhost
  port: 6379
