keyword: '{botname_lowercase}' # single word only. EX: tag, battlestars, manager, dua, notes
app:
  defaultLanguage: 'en'
  commandSettings:
    ignoreOfficialBots: true

redis:
  host: localhost
  port: 6379
